apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-rollouts-config-reader
  namespace: argo-rollouts
rules:
- apiGroups: ["", "coordination.k8s.io"]
  resources: ["configmaps", "leases"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-config-reader-binding
  namespace: argo-rollouts
subjects:
- kind: ServiceAccount
  name: argo-rollouts
  namespace: argo-rollouts
roleRef:
  kind: Role
  name: argo-rollouts-config-reader
  apiGroup: rbac.authorization.k8s.io