apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: deploy-app-

spec:
  serviceAccountName: argo-workflow
  entrypoint: deploy-pipeline

  arguments:
    parameters:
      - name: deployment-name
      - name: repo-url
      - name: image-name
      - name: tag
      - name: dockerfile-path
      - name: deployment-strategy
      - name: steps

  volumes:
    - name: workspace
      emptyDir: {}

    - name: docker-config
      secret:
        secretName: docker-registry-creds-secret
    

  templates:
    - name: deploy-pipeline
      steps:
        - - name: clone-repo
            template: git-clone
            arguments:
              parameters:
                - name: repo-url
                  value: "{{workflow.parameters.repo-url}}"

        - - name: build-image
            template: build-step
            arguments:
              parameters:
                - name: image-name
                  value: "{{workflow.parameters.image-name}}"
                - name: tag
                  value: "{{workflow.parameters.tag}}"
                - name: dockerfile-path
                  value: "{{workflow.parameters.dockerfile-path}}"
              artifacts:
                - name: repo
                  from: "{{steps.clone-repo.outputs.artifacts.repo}}"
        
        - - name: deploy-to-k8s
            template: deploy-step
            arguments:
              parameters:
                - name: deployment-name
                  value: "{{workflow.parameters.deployment-name}}"
                - name: image-name
                  value: "{{workflow.parameters.image-name}}"
                - name: tag
                  value: "{{workflow.parameters.tag}}"
                - name: deployment-strategy
                  value: "{{workflow.parameters.deployment-strategy}}"
                - name: steps
                  value: "{{workflow.parameters.steps}}"
                  
    - name: git-clone
      inputs:
        parameters:
          - name: repo-url

      outputs:
        artifacts:
          - name: repo
            path: /workspace
            s3:
              endpoint: s3.amazonaws.com
              bucket: canary-repos
              key: path/in/bucket/my-output-artifact.tgz
              accessKeySecret:
                name: repo-store-s3-credentials
                key: accessKey
              secretKeySecret:
                name: repo-store-s3-credentials
                key: secretKey

      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - git clone --progress --verbose {{inputs.parameters.repo-url}} /workspace

    - name: build-step
      inputs:
        parameters:
          - name: image-name
          - name: tag
          - name: dockerfile-path

        artifacts:
          - name: repo
            path: /workspace
            s3:
              endpoint: s3.amazonaws.com
              bucket: canary-repos
              #edit key to be more unique
              key: path/in/bucket/canary-artifact.tgz
              accessKeySecret:
                name: repo-store-s3-credentials
                key: accessKey
              secretKeySecret:
                name: repo-store-s3-credentials
                key: secretKey

      container:
        image: moby/buildkit:latest

        securityContext:
          privileged: true

        env:
          - name: DOCKER_CONFIG
            value: /docker-config

        volumeMounts:
          - name: docker-config
            mountPath: /docker-config/config.json
            subPath: .dockerconfigjson

        command: ["sh", "-c"]

        args:
          - |
            echo "Checking docker auth config..."
            if [ ! -f /docker-config/config.json ]; then
              echo "Docker config not found"
              exit 1
            fi

            cat /docker-config/config.json

            if ! grep -q "ghcr.io" /docker-config/config.json; then
              echo "No ghcr.io credentials found in docker config"
              exit 1
            fi

            DOCKERFILE_PATH="/workspace/{{inputs.parameters.dockerfile-path}}"
            DOCKERFILE_DIR="$(dirname "$DOCKERFILE_PATH")"

            echo "Checking for Dockerfile..."
            if [ ! -f "$DOCKERFILE_PATH" ]; then
              echo "Dockerfile NOT FOUND"
              echo "Looked for: $DOCKERFILE_PATH"
              exit 1
            fi

            echo "Building image with BuildKit..."

            buildctl-daemonless.sh build \
              --frontend dockerfile.v0 \
              --local context=/workspace \
              --local dockerfile="$DOCKERFILE_DIR" \
              --opt filename="$(basename "$DOCKERFILE_PATH")" \
              --output type=image,name=ghcr.io/canary-io/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}},push=true
      
    - name: deploy-step
      inputs:
        parameters:
          - name: deployment-name
          - name: image-name
          - name: tag
          - name: deployment-strategy
          - name: steps

      container:
        image: alpine/k8s:1.32.13
        command: [sh, -c]
        env:
          - name: DOCKER_CONFIG
            value: /docker-config

        volumeMounts:
          - name: docker-config
            mountPath: /docker-config/config.json
            subPath: .dockerconfigjson
        args:
          - |
            if [ "{{inputs.parameters.deployment-strategy}}" = "canary" ]; then
              STRATEGY_FLAGS='--set rollout.canary.enabled=true --set rollout.bluegreen.enabled=false --set-json rollout.canary.steps=[{{inputs.parameters.steps}}]'
            elif [ "{{inputs.parameters.deployment-strategy}}" = "bluegreen" ]; then
              STRATEGY_FLAGS="--set rollout.canary.enabled=false --set rollout.bluegreen.enabled=true"
            else
              echo "Invalid deployment strategy: {{inputs.parameters.deployment-strategy}}"
              exit 1
            fi

            helm install {{inputs.parameters.deployment-name}}-release oci://ghcr.io/canary-io/charts/orcadeployment \
            --version 0.3.2 \
            --namespace argo-rollouts \
            --create-namespace \
            --set image.name={{inputs.parameters.image-name}} \
            --set image.repository=ghcr.io/canary-io/{{inputs.parameters.image-name}} \
            --set image.tag={{inputs.parameters.tag}} \
            --set image.imagePullSecret=docker-registry-creds-secret \
            $STRATEGY_FLAGS


            echo "exposing rollout"

            kubectl expose rollout {{inputs.parameters.image-name}} \
              --namespace=argo-rollouts \
              --port=80 \
              --target-port=8080 \
              --type=LoadBalancer \
              --dry-run=client -o yaml | kubectl apply -f - --validate=false

            kubectl expose rollout {{inputs.parameters.image-name}} \
              --namespace=argo-rollouts \
              --port=80 \
              --target-port=8081 \
              --type=LoadBalancer \
              --dry-run=client -o yaml | kubectl apply -f - --validate=false


            echo "getting rollout"
            kubectl get rollout {{inputs.parameters.image-name}} -n argo-rollouts
