apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deploy-app-

spec:
  serviceAccountName: argo-workflow
  entrypoint: deploy-pipeline

  arguments:
    parameters:
      - name: repo-url
      - name: image-name
      - name: tag

  volumes:
    - name: workspace
      emptyDir: {}

    - name: docker-config
      secret:
        secretName: docker-registry-creds-secret
    

  templates:
    - name: deploy-pipeline
      steps:
        - - name: clone-repo
            template: git-clone
            arguments:
              parameters:
                - name: repo-url
                  value: "{{workflow.parameters.repo-url}}"

        - - name: build-image
            template: build-step
            arguments:
              parameters:
                - name: image-name
                  value: "{{workflow.parameters.image-name}}"
                - name: tag
                  value: "{{workflow.parameters.tag}}"
              artifacts:
                - name: repo
                  from: "{{steps.clone-repo.outputs.artifacts.repo}}"
        
        - - name: deploy-to-k8s
            template: deploy-step
            arguments:
              parameters:
                - name: image-name
                  value: "{{workflow.parameters.image-name}}"
                - name: tag
                  value: "{{workflow.parameters.tag}}"
                  
    - name: git-clone
      inputs:
        parameters:
          - name: repo-url

      outputs:
        artifacts:
          - name: repo
            path: /workspace
            s3:
              endpoint: s3.amazonaws.com
              bucket: canary-repos
              key: path/in/bucket/my-output-artifact.tgz
              accessKeySecret:
                name: repo-store-s3-credentials
                key: accessKey
              secretKeySecret:
                name: repo-store-s3-credentials
                key: secretKey

      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - git clone --progress --verbose {{inputs.parameters.repo-url}} /workspace

    - name: build-step
      inputs:
        parameters:
          - name: image-name
          - name: tag

        artifacts:
          - name: repo
            path: /workspace
            s3:
              endpoint: s3.amazonaws.com
              bucket: canary-repos
              #edit key to be more unique
              key: path/in/bucket/canary-artifact.tgz
              accessKeySecret:
                name: repo-store-s3-credentials
                key: accessKey
              secretKeySecret:
                name: repo-store-s3-credentials
                key: secretKey

      container:
        image: moby/buildkit:latest

        securityContext:
          privileged: true

        env:
          - name: DOCKER_CONFIG
            value: /docker-config

        volumeMounts:
          - name: docker-config
            mountPath: /docker-config/config.json
            subPath: .dockerconfigjson

        command: ["sh", "-c"]

        args:
          - |

            echo "Checking for Dockerfile..."
            if [ ! -f /workspace/Dockerfile ]; then
              echo "Dockerfile NOT FOUND"
              exit 1
            fi

            echo "Building image with BuildKit..."

            buildctl-daemonless.sh build \
              --frontend dockerfile.v0 \
              --local context=/workspace \
              --local dockerfile=/workspace \
              --output type=image,name=ghcr.io/canary-io/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}},push=true
      
    - name: deploy-step
      inputs:
        parameters:
          - name: image-name
          - name: tag

      container:
        image: alpine/k8s:1.32.13
        command: [sh, -c]
        env:
          - name: DOCKER_CONFIG
            value: /docker-config

        volumeMounts:
          - name: docker-config
            mountPath: /docker-config/config.json
            subPath: .dockerconfigjson
        args:
          - |

            helm install my-release oci://ghcr.io/josephjophy/orcadeployment --version 0.1.0   --set image.name={{inputs.parameters.image-name}}   --set image.tag={{tag}}  --set image.imagePullSecret[0].name=docker-registry-creds-secret

            echo "exposing rollout"

            kubectl expose rollout {{inputs.parameters.image-name}} \
              --namespace=argo-rollouts \
              --port=80 \
              --target-port=8080 \
              --type=LoadBalancer \
              --dry-run=client -o yaml | kubectl apply -f - --validate=false

            kubectl expose rollout {{inputs.parameters.image-name}} \
              --namespace=argo-rollouts \
              --port=80 \
              --target-port=8081 \
              --type=LoadBalancer \
              --dry-run=client -o yaml | kubectl apply -f - --validate=false


            echo "getting rollout"
            kubectl get rollout {{inputs.parameters.image-name}} -n argo-rollouts