apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: argo
rules:
  - apiGroups: ["", "apps", "argoproj.io", "networking.k8s.io"]
    resources: ["pods", "pods/log", "deployments", "services", "rollouts", "ingresses", "secrets", "workflowtaskresults"]
    verbs: ["get", "watch", "list", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-ingress-reader
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-ingress-reader-binding
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflow-ingress-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-rollouts-role
  namespace: argo-rollouts
rules:
  - apiGroups: ["", "apps", "argoproj.io", "networking.k8s.io"]
    resources: ["pods", "pods/log", "deployments", "services", "rollouts", "configmaps", "ingresses", "secrets", "analysistemplates", "namespaces"]
    verbs: ["get", "watch", "list", "create", "patch", "delete", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rollouts-binding
  namespace: argo-rollouts
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-rollouts-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-podmonitor-role
  namespace: monitoring
rules:
  - apiGroups: ["", "monitoring.coreos.com", "batch"]
    resources: ["podmonitors", "configmaps","jobs", "secrets"]
    verbs: ["get", "watch", "list", "create", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-podmonitor-binding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-podmonitor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-crd-reader
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-crd-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-crd-reader
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: argo