apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiam9zZXBoam9waHkiLCJwYXNzd29yZCI6ImdocF9wTlV2UmhrUmdCeU9MNTdPSldWSXFNWFNJRUxDaUMwaGZ5czYiLCJlbWFpbCI6IjM4MTVodW50ZXJzQGdtYWlsLmNvbSIsImF1dGgiOiJhbTl6WlhCb2FtOXdhSGs2WjJod1gzQk9WWFpTYUd0U1owSjVUMHcxTjA5S1YxWkpjVTFZVTBsRlRFTnBRekJvWm5sek5nPT0ifX19
kind: Secret
metadata:
  name: docker-registry-creds-secret
  namespace: argo
type: kubernetes.io/dockerconfigjson
