apiVersion: v1
kind: Secret
metadata:
  name: grafana-import-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: NTsIOBaEsfOT02CKhshRjDuI22TYf2taF368w48k
