apiVersion: v1
data:
  accessKey: QUtJQVZZT1JHQk9XMzVMNUZSRkE=
  secretKey: Y20xL3cwZnFVaVNuK01oYTFjQy8zRE00bC9LKy82RWp0MWNPTzBpQQ==
kind: Secret
metadata:
  name: repo-store-s3-credentials
  namespace: argo
